import {LoaderCircle,Sparkles} from 'lucide-react';
import {districtNames,type AnalysisResult,type Selection} from '../types';
import {number} from '../lib/format';
function Items({title,values}:{title:string;values:string[]}){return <div><h4>{title}</h4>{values.length?<ul>{values.map((v,i)=><li key={i}>{v}</li>)}</ul>:<p className="muted">Сервер бұл бөлімге тармақ бермеді.</p>}</div>;}
export function DecisionList({decisions}:{decisions:Selection}){return <ul>{decisions.map(d=><li key={d.actionId}>{d.actionId} · {d.districtId?districtNames[d.districtId]??d.districtId:'Бүкіл қала'}</li>)}</ul>;}
export function AIAnalysisPanel({analysis,loading,error,available,onAnalyze,demo}:{analysis:AnalysisResult|null;loading:boolean;error:string|null;available:boolean;onAnalyze:()=>void;demo:boolean}){
  const c=analysis?.analysis;
  const cards=[{title:'🏙️ Саясат талдаушысы',role:'Policy Analyst'},{title:'⚠️ Тәуекел агенті',role:'Risk Agent'},{title:'📈 Оңтайландыру агенті',role:'Optimizer Agent'},{title:'🧠 Қорытынды ұсыным',role:'Executive Recommendation'}];
  return <section className="panel council-panel" id="council" aria-busy={loading}><div className="section-heading"><div><span className="step-label">04 · AI КЕҢЕСІ</span><h2>Төрт көзқарас. Бір шешім.</h2></div><button className="primary-button" disabled={!available||loading} onClick={onAnalyze}>{loading?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>} {loading?'Кеңес дайындалуда…':'AI кеңесін алу'}</button></div>
    <p className="section-description">{demo ? "Демо кеңесі: дайын үлгі мәтіндер, нақты AI сұранымы орындалмайды." : "AI серверде есептелген нәтижелерді түсіндіреді. Алдымен симуляцияны аяқтаңыз."}</p>
    {error&&<p className="inline-error" role="alert">{error}</p>}{analysis?.message&&<p className="inline-error" role="status">{analysis.message}</p>}
    <div className="council-grid">{cards.map((card,i)=><article className="council-card" key={card.role}><span className="agent-role">{card.role}</span><h3>{card.title}</h3>
      {!c?<p className="muted">{loading?'Сервер жауабы күтілуде…':'Кеңес сұратылғаннан кейін жауап осында көрсетіледі.'}</p>:i===0?<><p>{c.policy.summary}</p><Items title="Күшті жақтары" values={c.policy.strengths}/><Items title="Теңгерім мен ымыралар" values={c.policy.tradeoffs}/><Items title="Аудандар туралы" values={c.policy.district_observations}/></>:i===1?<><p>Тәуекел деңгейі: {{low:'төмен',medium:'орташа',high:'жоғары'}[c.risk.risk_level]??c.risk.risk_level}</p><Items title="Тәуекелдер" values={c.risk.risks}/><Items title="Критикалық тұстар" values={c.risk.critical_findings}/><Items title="Ескертулер" values={c.risk.warnings}/></>:i===2?<><p>{c.optimizer.reasoning??'Сервер түсіндірме бермеді.'}</p><p>Ұсынылған Score: <strong>{number(c.optimizer.recommended_score)}</strong></p><p>Күтілетін өзгеріс: <strong>{c.optimizer.improvement>0?'+':''}{number(c.optimizer.improvement)}</strong></p><h4>Ұсынылған сценарий</h4><DecisionList decisions={c.optimizer.recommended_scenario}/></>:<><p>{c.executive.executive_summary}</p><Items title="Негізгі артықшылықтар" values={c.executive.top_strengths}/><Items title="Негізгі тәуекелдер" values={c.executive.main_risks}/><Items title="Ұсынылатын әрекеттер" values={c.executive.recommended_actions}/><h4>Соңғы ұсыным</h4><p>{c.executive.final_comment}</p></>}
    </article>)}</div>
  </section>;
}
